/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Entidades;

/**
 *
 * @author nsandoval
 */
public class EventoT2Frame extends javax.swing.JFrame {

    /**
     * Creates new form ContactoT1Frame
     */
    public EventoT2Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlabelNombre = new javax.swing.JLabel();
        JlabelTitulo = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        JlabelLugar = new javax.swing.JLabel();
        lugarTxt = new javax.swing.JTextField();
        JlabelNombreConvencion = new javax.swing.JLabel();
        nombreConvencionTxt = new javax.swing.JTextField();
        JlabelCatidadAsistentes = new javax.swing.JLabel();
        JlabelFecha = new javax.swing.JLabel();
        cantidadAsistentesTxt = new javax.swing.JTextField();
        fechaTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evento Tipo 2");

        JlabelNombre.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        JlabelNombre.setText("Nombre:");

        JlabelTitulo.setFont(new java.awt.Font("Century", 3, 16)); // NOI18N
        JlabelTitulo.setText("Evento Tipo 2");

        nombreTxt.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N
        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });


        JlabelLugar.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        JlabelLugar.setText("Lugar:");

        lugarTxt.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N

        JlabelNombreConvencion.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        JlabelNombreConvencion.setText("Convencion:");

        nombreConvencionTxt.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N

        JlabelCatidadAsistentes.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        JlabelCatidadAsistentes.setText("Cant Asistentes:");

        cantidadAsistentesTxt.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N
        
        JlabelFecha.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        JlabelFecha.setText("Fecha:");
        
        fechaTxt.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlabelNombre)
                            .addComponent(JlabelLugar)
                            .addComponent(JlabelNombreConvencion)
                            .addComponent(JlabelCatidadAsistentes)
                            .addComponent(JlabelFecha))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreTxt)
                            .addComponent(lugarTxt)
                            .addComponent(nombreConvencionTxt)
                            .addComponent(cantidadAsistentesTxt)
                            .addComponent(fechaTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(JlabelTitulo)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JlabelTitulo)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlabelNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlabelLugar)
                    .addComponent(lugarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlabelNombreConvencion)
                    .addComponent(nombreConvencionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlabelCatidadAsistentes)
                    .addComponent(cantidadAsistentesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlabelFecha)
                    .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactoT1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactoT1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactoT1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactoT1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactoT1Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelCatidadAsistentes;
    private javax.swing.JLabel JlabelFecha;
    private javax.swing.JLabel JlabelNombre;
    private javax.swing.JLabel JlabelLugar;
    private javax.swing.JLabel JlabelNombreConvencion;
    private javax.swing.JLabel JlabelTitulo;
    public javax.swing.JTextField cantidadAsistentesTxt;
    public javax.swing.JTextField fechaTxt;
    public javax.swing.JTextField lugarTxt;
    public javax.swing.JTextField nombreTxt;
    public javax.swing.JTextField nombreConvencionTxt;
    // End of variables declaration//GEN-END:variables{
}
